### ISSUE TITLE
The result of traceroute is always len(hops) = 1

### ISSUE THREAD

**Issue by coffeemasterHimself** [ValentinBELYN/icmplib#14]
Hi,

I use python 3.8.2 on windows and everytime I try to execute traceroute I'll get a len(hops) == 1

Are there any compatibiliy issues on Windows systems?

Environment:
Win 10 Pro
Python 3.8.2

Thanks for your help and

regards,

Coffeemaster

**Comment by ValentinBELYN** [comment]
Hi @coffeemasterHimself,

icmplib fully supports Windows. The behavior you are seeing is most likely related to your firewall. Can you try to deactivate it during the test and try again? There are other issues on this subject (#7, #8 and #10).
