### ISSUE TITLE
Traceroute: avg_rtt should be divided by packets_received

### ISSUE THREAD

**Issue by patrickfnielsen** [ValentinBELYN/icmplib#16]
In the traceroute module "avg_rtt" does not return the average but the total round trip.

Looking at how its implemented for the ping module, the following is missing:
```
    if packets_received:
        avg_rtt /= packets_received
```

I'll be happy to create a PR if you want, though it's a simple fix.

**Comment by ValentinBELYN** [comment]
Oh, I don't even know how I didn't see it! :sweat_smile:

If you have time, I will be happy to validate your PR. Otherwise I can take care of it this weekend. I am very busy this week.

Thanks for reporting this issue 👍
