### ISSUE TITLE
ping and ICMPReply does not contain ttl information for IPv4

### ISSUE THREAD

**Issue by leo-liu** [ValentinBELYN/icmplib#2]
I notice that both high level `ping`/`multiping` and low level `ICMPReply` do not contain ttl information, which is useful.

And I think it is easy to  retrive the ttl in `ICMPv4Socket`

**Comment by ValentinBELYN** [comment]
You are right. This is a useful information.
Besides, I have already noticed and implemented it, but the code is not yet committed. I work in parallel on other projects, which leaves me less time at the moment. I hope to commit this week.

**Comment by ValentinBELYN** [comment]
icmplib was designed to offer features based on the `ICMPv4` and `ICMPv6` protocols. If I add a functionality on `ICMPv4`, I have to do the same with `ICMPv6` to stay consistent and not create asymmetry. Unfortunately, I have no way of accessing the `IPv6` header to retrieve the information you want.

I keep the idea in mind but for the moment I close this issue. Thanks for contributing.
