### ISSUE TITLE
Feature Request - Add source parameter to select an interface to ping from.

### ISSUE THREAD

**Issue by shreyaskapale** [ValentinBELYN/icmplib#20]
Feature Request - **Add Source parameter to select an Interface to ping from.**

**Comment by ValentinBELYN** [comment]
Hi, it's already planned for version 2.0 which will be released by the end of the year 🎉
Don't hesitate if you have other suggestions 😄

**Comment by shreyaskapale** [comment]
Oh great ! i will close this issue then 🎉 It would be really great if it completes soon. I actually needed this for one of my projects. I will be waiting !

**Comment by ValentinBELYN** [comment]
I'll do my best :)

**Comment by ValentinBELYN** [comment]
Hi 👋

icmplib 2.0 is now available! All the foundations of the library have been completely reworked to make it even faster. You can now use the library without root privileges and set the source IP address of functions and sockets. 🎉
Hope you will like this new version!

[Click here to see the full changelog](https://github.com/ValentinBELYN/icmplib/blob/master/CHANGELOG.md)

**Comment by ValentinBELYN** [comment]
A huge thank you ❤️ Happy to read this!
