### ISSUE TITLE
Feature request: Listen for ICMP Echo Request messages

### ISSUE THREAD

**Issue by Duvio** [ValentinBELYN/icmplib#26]
Hi,

i think it would be nice if you would implement a function which listens for Echo Request packets as ICMPv4Socket.receive only returns Echo Reply packets.

Thanks!

**Comment by ValentinBELYN** [comment]
Hi, thank you for using this library 😃

Why not! It could be an interesting feature. Now that the library is based on a new software architecture, this should be possible.

However, this will not be implemented immediately. Other features are planned before.

**Comment by ValentinBELYN** [comment]
Hi @Duvio 👋

The task is more difficult than expected. I may have underestimated the amount of work and unfortunately, I don't have the time to devote to this feature. There is still a lot of work on the library. The version 3 of icmplib will be released next week and will notably include asynchronous functions.

I apologize for giving you false hope. 😢 There is always the possibility that this feature will be implemented in the future. However, I won't be against a little help!

For the moment, I close this issue. Thank you for your suggestion and sorry again.
