### ISSUE TITLE
ICMP server mode support

### ISSUE THREAD

**Issue by occoder** [ValentinBELYN/icmplib#4]
Thanks for bringing up such a sleek library.
This icmplib seems to only support ICMP client mode where the ping is initiated.
It would be better if it could support the ICMP server mode as well.
Cheers.

**Comment by ValentinBELYN** [comment]
Thanks for the compliment. It is nice to think that the work I do is useful ❤️

To answer your question, yes, icmplib focuses on the client aspect. All network devices are able to reply natively to ICMP requests. That is why icmplib does not include a server mode. Besides, I don't even know if it is possible.

I keep the idea in mind, maybe in a separate extension 😄
