### ISSUE TITLE
Multiping

### ISSUE THREAD

**Issue by AzPyCoder** [ValentinBELYN/icmplib#43]
Dear Valentin,
Can you add to a **icmplib** library function receive MAC address during multiping? 
Thanks.

**Comment by ValentinBELYN** [comment]
Hi @AzPyCoder,

I don't see the case for retrieving the MAC address during a ping, knowing that it is only useful for machines on the same network (for machines outside your network, you would see the MAC address of your gateway). In addition, it is difficult to access this information, especially in IPv6 where the Ethernet header is not accessible in Python.

So if you want to retrieve the MAC addresses, I recommend that you consult the arp table of your machine after the `multiping`.

Sorry for not being able to help you further.
