### ISSUE TITLE
Using icmplib without root permission

### ISSUE THREAD

**Issue by jabaa** [ValentinBELYN/icmplib#46]
Is it possible to use this library without root permission?

I'm using Kali Linux `kali 5.16.0-kali1-amd64 #1 SMP PREEMPT Debian 5.16.7-2kali1 (2022-02-10) x86_64 GNU/Linux` with Python 3.9 and icmplib-3.0.3. I can run `ping` in my terminal. I've checked 

    $ ls -l $(which ping)
    -rwxr-xr-x 1 root root 81600 Feb  5 05:37 /usr/bin/ping

As you can see, SUID and SGID isn't set. I've checked

    $ sysctl net.ipv4.ping_group_range
    net.ipv4.ping_group_range = 1   0

Obviously, `ping` can be run without root permission.

I've tried 

    from icmplib import ping
    ping('192.168.178.1', privileged=False)

and got

```
Traceback (most recent call last):
  File "/workdir/lib/python3.9/site-packages/icmplib/sockets.py", line 88, in __init__
    self._sock = self._create_socket(
  File "/workdir/lib/python3.9/site-packages/icmplib/sockets.py", line 486, in _create_socket
    return socket.socket(
  File "/usr/lib/python3.9/socket.py", line 232, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workdir/main.py", line 5, in <module>
    ping('192.168.178.1', privileged=False)
  File "/workdir/lib/python3.9/site-packages/icmplib/ping.py", line 141, in ping
    with _Socket(source, privileged) as sock:
  File "/workdir/lib/python3.9/site-packages/icmplib/sockets.py", line 97, in __init__
    raise SocketPermissionError(privileged)
icmplib.exceptions.SocketPermissionError: A prior configuration of your OS is required to use ICMP sockets without root privileges. Read more on https://github.com/ValentinBELYN/icmplib
```

I don't have permissions to change 

    sudo sysctl -w net.ipv4.ping_group_range='0 2147483647'

Is there a way to use this library? Is this problem related to the way this library works or is it a general Python problem?

**Comment by jabaa** [comment]
I got an answer to my last question. It's not a general Python problem. https://pypi.org/project/pyICMP/ works for me without any root permissions. That means, the problem is caused by the way how icmplib works or how I use it.

**Comment by sunwire** [comment]
> Obviously, `ping` can be run without root permission.

I think beacause Kali Linux is Debian based ping uses file capabilities
`getcap /usr/bin/ping`

**Comment by jabaa** [comment]
@sunwire Thank you. It seems, you're right. `/usr/bin/ping` has network capabilities:

    $ getcap $(which ping)
    /usr/bin/ping cap_net_raw=ep

I checked other libraries and the only way I've found, was to spawn a `ping` process. It looks like there is no way to use a Python library for this without `sudo` (at least once to configure the system) or `ping`.

**Comment by ValentinBELYN** [comment]
Hi!

Thanks @sunwire for answering @jabaa 👍

@jabaa Your problem is not related to the library directly. You must set the `net.ipv4.ping_group_range` parameter of your system to allow the use of datagram sockets (instead of raw sockets) for sending ICMP messages and therefore, to use the library without root privileges.

Related documentation:
https://github.com/ValentinBELYN/icmplib/blob/main/docs/6-use-icmplib-without-privileges.md

Otherwise, what do you mean by "I don't have permissions to change"?

As long as you have the result below (1 0), you will not be able to use this library without root privileges:
```shell
$ sysctl net.ipv4.ping_group_range
net.ipv4.ping_group_range = 1   0   # functionality disabled: no user, even root, can use datagram sockets for ICMP requests
```

**Comment by jabaa** [comment]
I've read this part of the documentation, but that's not possible for me. I have to distribute software to computer system that I don't have `sudo` access to. I can't 

    $ sudo sysctl -w net.ipv4.ping_group_range='0 2147483647'

I don't have the permissions and 

    $ sysctl -w net.ipv4.ping_group_range='0 2147483647'

without `sudo` doesn't work. My question was:

 My company gives me a laptop with Kali Linux without `sudo` permission. Is it possible to send a `ping` without the terminal program `ping`? It seems like it's not possible. This laptop is the dev/test environment the software is later deployed to.
