### ISSUE TITLE
TCP ping a specified port number

### ISSUE THREAD

**Issue by Bradly7412** [ValentinBELYN/icmplib#47]
I was wondering if it is possible to ping a specified port number when do this?

**Comment by ValentinBELYN** [comment]
Hi @Bradly7412,

The icmplib library focuses on the ICMP protocol (layer 3 of the OSI model). It does not deal with higher layer transport protocols such as UDP or TCP (layer 4). The notion of port does not exist in layer 3, and therefore the functionality you want cannot be implemented.

Other libraries will certainly be more appropriate to achieve this 😉
