### ISSUE TITLE
Multiping scale

### ISSUE THREAD

**Issue by Huthesh** [ValentinBELYN/icmplib#53]
How may host can we ping using multi ping. I tried with 1000 host. Ping was successful but CPU utilisation was more than 100%?
Is there a known issue?

**Comment by ValentinBELYN** [comment]
Hi @Huthesh 👋

The `multiping` function can take an infinite number of hosts. By default, it performs 50 pings simultaneously. If you find that your CPU load is too high, you can influence this parameter using the `concurrent_tasks` option.

```python
# Performs 25 pings simultaneously instead of 50
hosts = multiping(['10.0.0.5', '127.0.0.1', '::1', ...], concurrent_tasks=25)
```
