### ISSUE TITLE
Sad not to support 3.6

### ISSUE THREAD

**Issue by snail2sky** [ValentinBELYN/icmplib#58]
python 3.6 also supports asyncio, can you support python3.6 version, please

**Comment by ValentinBELYN** [comment]
Hi @snail2sky,

Thanks for opening this issue. However, I don't plan to go back to Python 3.6. Maintaining old versions is time consuming and Python 3.7 notably allows more modern code at the asyncio level.

Moreover, according to some [statistics](https://pypistats.org/packages/__all__), Python 3.6 would be used at less than 10% today.
