### ISSUE TITLE
Can only receive the last hop using traceroute on Windows

### ISSUE THREAD

**Issue by CarlGao4** [ValentinBELYN/icmplib#65]
As the pictures described: 

Windows 11:
![image](https://user-images.githubusercontent.com/57826826/230764902-c6c893ac-cc88-41b8-af6c-d9461894ba47.png)

WSL (Archlinux) on Windows 11:
![image](https://user-images.githubusercontent.com/57826826/230764763-ed337962-ca54-42ba-9ba2-3a993042fdd6.png)

**Comment by ValentinBELYN** [comment]
Hi 👋

The behavior you are seeing on Windows is most likely related to your firewall. Can you try to deactivate it during the test and try again? There are other issues on this subject (#7, #8 and #10).

**Comment by CarlGao4** [comment]
I've allowed all connections of python.exe but it is still like this. 
It's interesting that the problem is solved when the firewall (Windows Defender Firewall) has been disabled totally but only allowing python.exe can't.
I also suggest you to add this instruction to your README, or the programs using your library may not be able to function.

**Comment by ValentinBELYN** [comment]
I think you can make exceptions for the ICMP protocol on your firewall, which will save you from disabling it completely.

Otherwise, as soon as I have a little more time, I will try to add an FAQ or a space with frequently encountered problems.
