### ISSUE TITLE
Add reply payload retrieval and checking

### ISSUE THREAD

**Issue by YurBoiRene** [ValentinBELYN/icmplib#73]
A part of the `ping` command is that it sends a fixed payload and then will report an error if the returned data is different than the data sent. 

I noticed in icmplib you can send an arbitrary payload after the ICMP header but there is no support for reading the returned payload or checking if it is the same.

I would propose adding  `payload` property to the `ICMPReply` class as well as possibly a "valid packets" property in the `Host` class to report the number of packets that sent valid/invalid data back.

If you're interested in having this as a feature, I would be happy to implement and make a pull request.

**Comment by ValentinBELYN** [comment]
Hi @YurBoiRene,

Thanks for the suggestion. However, this is not planned at the moment.
