### ISSUE TITLE
The traceroute under ipv6 only displays the last hop

### ISSUE THREAD

**Issue by simple9s** [ValentinBELYN/icmplib#74]
Hi Valentine, thanks for the great library.I'm doing an experiment,and I had a small problem.
The traceroute under ipv6 only displays the last hop.
![image](https://github.com/ValentinBELYN/icmplib/assets/59346261/82d27976-574d-4d2b-9302-9538e55d3339)
But my use of windwos tools is normal.
![image](https://github.com/ValentinBELYN/icmplib/assets/59346261/337d3e5e-5760-4290-b3ac-3fbb8175cb3b)

Thanks again and regards.

**Comment by jaraco** [comment]
I encountered the same problem on IPv4 on Linux (with traceroute patched to support non-privileged execution):

```
 ~ @ pip-run jaraco.net
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import importlib
>>> isp = importlib.import_module('jaraco.net.ping-isp')
>>> isp._patch_traceroute_privilege()
>>> isp.icmplib.traceroute('www.google.com')
[<Hop 13 [142.251.35.164]>]
```

**Comment by jaraco** [comment]
Oh! Reading [this doc](https://github.com/ValentinBELYN/icmplib/blob/main/docs/6-use-icmplib-without-privileges.md), I see that "traceroute" needs privileged execution for the TTL to work. Interestingly, here's what I've found:

- On Linux, setting `privileged=False` causes the undesirable behavior (only the last hop is recorded).
- On Windows, privileged is forced to False, so presumably may be the cause for only getting the last hop.
- On macOS, I am able to set `privileged=False` and get reasonable results back from a traceroute.

**Comment by ValentinBELYN** [comment]
Hi @simple9s,

The behavior you are seeing on Windows is most likely related to your firewall. Can you try to temporarily deactivate it during the test and try again? There are other issues on this subject (#7, #8 and #10).

**Comment by simple9s** [comment]
> Hi @simple9s,
> 
> The behavior you are seeing on Windows is most likely related to your firewall. Can you try to temporarily deactivate it during the test and try again? There are other issues on this subject (#7, #8 and #10).

Thank you for your reply. This is really a firewall problem.

**Comment by simple9s** [comment]
> Oh! Reading [this doc](https://github.com/ValentinBELYN/icmplib/blob/main/docs/6-use-icmplib-without-privileges.md), I see that "traceroute" needs privileged execution for the TTL to work. Interestingly, here's what I've found:
> 
> * On Linux, setting `privileged=False` causes the undesirable behavior (only the last hop is recorded).
> * On Windows, privileged is forced to False, so presumably may be the cause for only getting the last hop.
> * On macOS, I am able to set `privileged=False` and get reasonable results back from a traceroute.

Thanks for your explanation, but windows is the firewall problem as the author said.
