### ISSUE TITLE
Whats the difference between icmpLib and the icmpLibv2(forked from IcmpLib) ? 

### ISSUE THREAD

**Issue by tkekan** [ValentinBELYN/icmplib#75]

**Comment by jaraco** [comment]
[icmplibv2](https://pypi.org/project/icmplibv2/) appears to be an unauthorized fork of icmplib. The releases did not even update the homepage of the project, so it's not straightforward to trace the source of icmplibv2.

Looking at the [forks of this project](https://github.com/ValentinBELYN/icmplib/forks?include=active&page=1&period=5y&sort_by=stargazer_counts) in GitHub, I don't see anything that resembles the author of icmplibv2 in PyPI.

Moreover, icmplibv2 has only two releases in 2020, so appears to be abandoned.

Someone could theoretically download the source for the latest release of icmplibv2 and apply it over a checkout of icmplib from that time and produce a diff, but my recommendation would be to ignore icmplibv2.

**Comment by ValentinBELYN** [comment]
`icmplibv2` is not developed by me. It is indeed a fork of my library (everything has been forked even my name and email without modification...). Furthermore, it does not seem to be maintained.

You should avoid using it. I don't know if it's possible to report it to request its removal. I think many people might make a mistake downloading it.

**Comment by jaraco** [comment]
> I don't know if it's possible to report it to request its removal.

Reading through [PEP 541](https://peps.python.org/pep-0541/), I don't see anything about removing packages with similar names that aren't specifically abusive.

There is a section on [continued maintenance of an abandoned project](https://peps.python.org/pep-0541/#continued-maintenance-of-an-abandoned-project). Here's what could happen:

- Request to maintain icmplibv2 based on abandonment criteria
- After obtaining maintenance access, redirect users of that project to the maintained project.
