### ISSUE TITLE
Problem with traceroute

### ISSUE THREAD

**Issue by scialuppa** [ValentinBELYN/icmplib#8]
Hi, sorry for my bad english.
My problem is that I tried your "traceroute.py" example but it doesn't work.
He tells me that "Some routers are not responding" but if I ping from the cmd with various ttl, it works.
![Cattura](https://user-images.githubusercontent.com/66923428/84604662-d7adae80-ae97-11ea-8053-57f15156c47f.PNG)

**Comment by ValentinBELYN** [comment]
This problem may be related to your firewall. Can you try to deactivate it during the test and try again? I just tested on several virtual machines and it works correctly.

Your problem seems similar to the issue #7.

**Comment by scialuppa** [comment]
Thanks it worked.
I created a new rule coming into the firewall by enabling ICMPv4 protocol on all types.
