### ISSUE TITLE
Responses are not linked to requests

### ISSUE THREAD

**Issue by MasterCarl** [ValentinBELYN/icmplib#9]
There seems to be a problem with matching incoming responses to requests.
If I 

1. send an ICMP request that times out after 200ms,
1. send another one at 250 milliseconds, and
1. get a reply to the first request at 255 milliseconds,

I get a reported round trip time of **5 milliseconds** for the second request, even if that probably will take longer.
There should be some kind of mechanism to validate that any response receives actually matches the current request so that previous answers don't throw off the results.

**Comment by ValentinBELYN** [comment]
There is already a mechanism that links responses to requests. To do this, you must ensure that requests have a unique id / sequence pair for each request as defined in the RFC.

**Comment by MasterCarl** [comment]
Sorry, my bad. I added a unique ID parameter for each request and it does indeed work now. Thanks for checking so fast!

**Comment by ValentinBELYN** [comment]
You're welcome 😄
